name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  'tests':
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Tests
      run: |
        pip install tox
        tox -epy3
    - name: Lint
      run: |
        pip install tox
        tox -eisort,black
